why not make things prettier

diff --git a/layout/DEBIAN/postrm b/layout/DEBIAN/postrm
--- a/layout/DEBIAN/postrm
+++ b/layout/DEBIAN/postrm
@@ -1,4 +1,11 @@
-#! /bin/sh
+#!/bin/sh
 
 echo Reloading daemon
-killall -TERM kbd 2>/dev/null || true
+if launchctl unload -wF /System/Library/LaunchDaemons/com.apple.TextInput.kbd.plist 2>/dev/null; then
+  launchctl load -wF /System/Library/LaunchDaemons/com.apple.TextInput.kbd.plist 2>/dev/null || true
+else
+  # Elucubratus launchctl may fail, fallback to killall
+  killall -TERM kbd 2>/dev/null || true
+fi
+
+exit 0
